---
- hosts: all
  vars:
   username: "{{ name1 }}"
   newpassword: "{{ newpass }}"
  tasks:
   - name: Checking user
     win_shell: |
      [String]$username1= "{{ username }}"
      Get-ADUser -Filter {(Name -eq $username1)} -SearchBase "CN=$username1,CN=Partition1,DC=LTI,DC=com" -Server 'WindowsAD:50000'
     notify:
      - task2
  handlers:
   - name: task2
     win_shell: |
      [String]$username1= "{{ username }}"
      $sucess=Get-ADUser -Filter {(Name -eq $username1)} -SearchBase "CN=Partition1,DC=LTI,DC=com" -Server 'WindowsAD:50000'
      if($sucess -ne $null)
      {
       $pass= "{{ newpassword }}"
       $newpass= ConvertTo-SecureString $pass -AsPlainText -Force
       Set-ADAccountPassword -Identity "CN=$username1,CN=Partition1,DC=LTI,DC=com" -Server 'WindowsAD:50000' -NewPassword $newpass -Reset
       }
